# Generated by Django 4.0.4 on 2022-05-15 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(null=1, on_delete=django.db.models.deletion.PROTECT, to='blog.category'),
        ),
    ]
